# Generated by Django 5.0.6 on 2026-05-10 04:36

import django.db.models.deletion
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path)),
                ('is_default', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.candidateprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
